#ifndef __OPENCV_ALL__
#define __OPENCV_ALL__

// Project Configuration in MSVS
// - C/C++ > General > Additional Include Directories: EXTERNAL\OpenCV\include
// - Linker > Additional Library Directories: EXTERNAL\OpenCV\lib

#ifdef _WIN32
#   pragma warning(disable: 4819) // Diable warnings related to OpenCV's code page (949) problem
#endif

#define DISABLE_OPENCV_24_COMPATIBILITY

#include <opencv2/opencv.hpp>
#include <opencv2/aruco.hpp>
#include <opencv2/bgsegm.hpp>
#include <opencv2/bioinspired.hpp>
#include <opencv2/ccalib.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/dpm.hpp>
#include <opencv2/face.hpp>
#include <opencv2/fuzzy.hpp>
#include <opencv2/line_descriptor.hpp>
#include <opencv2/optflow.hpp>
#include <opencv2/plot.hpp>
#include <opencv2/rgbd.hpp>
#include <opencv2/saliency.hpp>
#include <opencv2/stereo.hpp>
#include <opencv2/structured_light.hpp>
#include <opencv2/surface_matching.hpp>
#include <opencv2/text.hpp>
#include <opencv2/tracking.hpp>
#include <opencv2/viz.hpp>
#include <opencv2/xfeatures2d.hpp>
#include <opencv2/ximgproc.hpp>
#include <opencv2/xobjdetect.hpp>
#include <opencv2/xphoto.hpp>

#ifdef _WIN32
#   ifdef _DEBUG
#       pragma comment(lib, "IlmImfd.lib")
#       pragma comment(lib, "ippicvmt.lib")
#       pragma comment(lib, "libjasperd.lib")
#       pragma comment(lib, "libjpegd.lib")
#       pragma comment(lib, "libpngd.lib")
#       pragma comment(lib, "libprotobufd.lib")
#       pragma comment(lib, "libtiffd.lib")
#       pragma comment(lib, "libwebpd.lib")
#       pragma comment(lib, "zlibd.lib")
#       pragma comment(lib, "opencv_aruco310d.lib")
#       pragma comment(lib, "opencv_bgsegm310d.lib")
#       pragma comment(lib, "opencv_bioinspired310d.lib")
#       pragma comment(lib, "opencv_calib3d310d.lib")
#       pragma comment(lib, "opencv_ccalib310d.lib")
#       pragma comment(lib, "opencv_core310d.lib")
#       pragma comment(lib, "opencv_datasets310d.lib")
#       pragma comment(lib, "opencv_dnn310d.lib")
#       pragma comment(lib, "opencv_dpm310d.lib")
#       pragma comment(lib, "opencv_face310d.lib")
#       pragma comment(lib, "opencv_features2d310d.lib")
#       pragma comment(lib, "opencv_flann310d.lib")
#       pragma comment(lib, "opencv_fuzzy310d.lib")
#       pragma comment(lib, "opencv_highgui310d.lib")
#       pragma comment(lib, "opencv_imgcodecs310d.lib")
#       pragma comment(lib, "opencv_imgproc310d.lib")
#       pragma comment(lib, "opencv_line_descriptor310d.lib")
#       pragma comment(lib, "opencv_ml310d.lib")
#       pragma comment(lib, "opencv_objdetect310d.lib")
#       pragma comment(lib, "opencv_optflow310d.lib")
#       pragma comment(lib, "opencv_photo310d.lib")
#       pragma comment(lib, "opencv_plot310d.lib")
#       pragma comment(lib, "opencv_reg310d.lib")
#       pragma comment(lib, "opencv_rgbd310d.lib")
#       pragma comment(lib, "opencv_saliency310d.lib")
#       pragma comment(lib, "opencv_shape310d.lib")
#       pragma comment(lib, "opencv_stereo310d.lib")
#       pragma comment(lib, "opencv_stitching310d.lib")
#       pragma comment(lib, "opencv_structured_light310d.lib")
#       pragma comment(lib, "opencv_superres310d.lib")
#       pragma comment(lib, "opencv_surface_matching310d.lib")
#       pragma comment(lib, "opencv_text310d.lib")
#       pragma comment(lib, "opencv_tracking310d.lib")
#       pragma comment(lib, "opencv_video310d.lib")
#       pragma comment(lib, "opencv_videoio310d.lib")
#       pragma comment(lib, "opencv_videostab310d.lib")
#       pragma comment(lib, "opencv_viz310d.lib")
#       pragma comment(lib, "opencv_xfeatures2d310d.lib")
#       pragma comment(lib, "opencv_ximgproc310d.lib")
#       pragma comment(lib, "opencv_xobjdetect310d.lib")
#       pragma comment(lib, "opencv_xphoto310d.lib")

#       ifdef _EVL_USE_VIZ
#           pragma comment(lib, "vtkalglib-6.3d.lib")
#           pragma comment(lib, "vtkChartsCore-6.3d.lib")
#           pragma comment(lib, "vtkCommonColor-6.3d.lib")
#           pragma comment(lib, "vtkCommonComputationalGeometry-6.3d.lib")
#           pragma comment(lib, "vtkCommonCore-6.3d.lib")
#           pragma comment(lib, "vtkCommonDataModel-6.3d.lib")
#           pragma comment(lib, "vtkCommonExecutionModel-6.3d.lib")
#           pragma comment(lib, "vtkCommonMath-6.3d.lib")
#           pragma comment(lib, "vtkCommonMisc-6.3d.lib")
#           pragma comment(lib, "vtkCommonSystem-6.3d.lib")
#           pragma comment(lib, "vtkCommonTransforms-6.3d.lib")
#           pragma comment(lib, "vtkDICOMParser-6.3d.lib")
#           pragma comment(lib, "vtkDomainsChemistry-6.3d.lib")
#           pragma comment(lib, "vtkexoIIc-6.3d.lib")
#           pragma comment(lib, "vtkexpat-6.3d.lib")
#           pragma comment(lib, "vtkFiltersAMR-6.3d.lib")
#           pragma comment(lib, "vtkFiltersCore-6.3d.lib")
#           pragma comment(lib, "vtkFiltersExtraction-6.3d.lib")
#           pragma comment(lib, "vtkFiltersFlowPaths-6.3d.lib")
#           pragma comment(lib, "vtkFiltersGeneral-6.3d.lib")
#           pragma comment(lib, "vtkFiltersGeneric-6.3d.lib")
#           pragma comment(lib, "vtkFiltersGeometry-6.3d.lib")
#           pragma comment(lib, "vtkFiltersHybrid-6.3d.lib")
#           pragma comment(lib, "vtkFiltersHyperTree-6.3d.lib")
#           pragma comment(lib, "vtkFiltersImaging-6.3d.lib")
#           pragma comment(lib, "vtkFiltersModeling-6.3d.lib")
#           pragma comment(lib, "vtkFiltersParallel-6.3d.lib")
#           pragma comment(lib, "vtkFiltersParallelImaging-6.3d.lib")
#           pragma comment(lib, "vtkFiltersProgrammable-6.3d.lib")
#           pragma comment(lib, "vtkFiltersSelection-6.3d.lib")
#           pragma comment(lib, "vtkFiltersSMP-6.3d.lib")
#           pragma comment(lib, "vtkFiltersSources-6.3d.lib")
#           pragma comment(lib, "vtkFiltersStatistics-6.3d.lib")
#           pragma comment(lib, "vtkFiltersTexture-6.3d.lib")
#           pragma comment(lib, "vtkFiltersVerdict-6.3d.lib")
#           pragma comment(lib, "vtkfreetype-6.3d.lib")
#           pragma comment(lib, "vtkftgl-6.3d.lib")
#           pragma comment(lib, "vtkGeovisCore-6.3d.lib")
#           pragma comment(lib, "vtkgl2ps-6.3d.lib")
#           pragma comment(lib, "vtkhdf5-6.3d.lib")
#           pragma comment(lib, "vtkhdf5_hl-6.3d.lib")
#           pragma comment(lib, "vtkImagingColor-6.3d.lib")
#           pragma comment(lib, "vtkImagingCore-6.3d.lib")
#           pragma comment(lib, "vtkImagingFourier-6.3d.lib")
#           pragma comment(lib, "vtkImagingGeneral-6.3d.lib")
#           pragma comment(lib, "vtkImagingHybrid-6.3d.lib")
#           pragma comment(lib, "vtkImagingMath-6.3d.lib")
#           pragma comment(lib, "vtkImagingMorphological-6.3d.lib")
#           pragma comment(lib, "vtkImagingSources-6.3d.lib")
#           pragma comment(lib, "vtkImagingStatistics-6.3d.lib")
#           pragma comment(lib, "vtkImagingStencil-6.3d.lib")
#           pragma comment(lib, "vtkInfovisCore-6.3d.lib")
#           pragma comment(lib, "vtkInfovisLayout-6.3d.lib")
#           pragma comment(lib, "vtkInteractionImage-6.3d.lib")
#           pragma comment(lib, "vtkInteractionStyle-6.3d.lib")
#           pragma comment(lib, "vtkInteractionWidgets-6.3d.lib")
#           pragma comment(lib, "vtkIOAMR-6.3d.lib")
#           pragma comment(lib, "vtkIOCore-6.3d.lib")
#           pragma comment(lib, "vtkIOEnSight-6.3d.lib")
#           pragma comment(lib, "vtkIOExodus-6.3d.lib")
#           pragma comment(lib, "vtkIOExport-6.3d.lib")
#           pragma comment(lib, "vtkIOGeometry-6.3d.lib")
#           pragma comment(lib, "vtkIOImage-6.3d.lib")
#           pragma comment(lib, "vtkIOImport-6.3d.lib")
#           pragma comment(lib, "vtkIOInfovis-6.3d.lib")
#           pragma comment(lib, "vtkIOLegacy-6.3d.lib")
#           pragma comment(lib, "vtkIOLSDyna-6.3d.lib")
#           pragma comment(lib, "vtkIOMINC-6.3d.lib")
#           pragma comment(lib, "vtkIOMovie-6.3d.lib")
#           pragma comment(lib, "vtkIONetCDF-6.3d.lib")
#           pragma comment(lib, "vtkIOParallel-6.3d.lib")
#           pragma comment(lib, "vtkIOParallelXML-6.3d.lib")
#           pragma comment(lib, "vtkIOPLY-6.3d.lib")
#           pragma comment(lib, "vtkIOSQL-6.3d.lib")
#           pragma comment(lib, "vtkIOVideo-6.3d.lib")
#           pragma comment(lib, "vtkIOXML-6.3d.lib")
#           pragma comment(lib, "vtkIOXMLParser-6.3d.lib")
#           pragma comment(lib, "vtkjpeg-6.3d.lib")
#           pragma comment(lib, "vtkjsoncpp-6.3d.lib")
#           pragma comment(lib, "vtklibxml2-6.3d.lib")
#           pragma comment(lib, "vtkmetaio-6.3d.lib")
#           pragma comment(lib, "vtkNetCDF-6.3d.lib")
#           pragma comment(lib, "vtkNetCDF_cxx-6.3d.lib")
#           pragma comment(lib, "vtkoggtheora-6.3d.lib")
#           pragma comment(lib, "vtkParallelCore-6.3d.lib")
#           pragma comment(lib, "vtkpng-6.3d.lib")
#           pragma comment(lib, "vtkproj4-6.3d.lib")
#           pragma comment(lib, "vtkRenderingAnnotation-6.3d.lib")
#           pragma comment(lib, "vtkRenderingContext2D-6.3d.lib")
#           pragma comment(lib, "vtkRenderingContextOpenGL-6.3d.lib")
#           pragma comment(lib, "vtkRenderingCore-6.3d.lib")
#           pragma comment(lib, "vtkRenderingFreeType-6.3d.lib")
#           pragma comment(lib, "vtkRenderingGL2PS-6.3d.lib")
#           pragma comment(lib, "vtkRenderingImage-6.3d.lib")
#           pragma comment(lib, "vtkRenderingLabel-6.3d.lib")
#           pragma comment(lib, "vtkRenderingLIC-6.3d.lib")
#           pragma comment(lib, "vtkRenderingLOD-6.3d.lib")
#           pragma comment(lib, "vtkRenderingOpenGL-6.3d.lib")
#           pragma comment(lib, "vtkRenderingVolume-6.3d.lib")
#           pragma comment(lib, "vtkRenderingVolumeOpenGL-6.3d.lib")
#           pragma comment(lib, "vtksqlite-6.3d.lib")
#           pragma comment(lib, "vtksys-6.3d.lib")
#           pragma comment(lib, "vtktiff-6.3d.lib")
#           pragma comment(lib, "vtkverdict-6.3d.lib")
#           pragma comment(lib, "vtkViewsContext2D-6.3d.lib")
#           pragma comment(lib, "vtkViewsCore-6.3d.lib")
#           pragma comment(lib, "vtkViewsInfovis-6.3d.lib")
#           pragma comment(lib, "vtkzlib-6.3d.lib")
#       endif // End of '_EVL_USE_VIZ'

#   else
#       pragma comment(lib, "IlmImf.lib")
#       pragma comment(lib, "ippicvmt.lib")
#       pragma comment(lib, "libjasper.lib")
#       pragma comment(lib, "libjpeg.lib")
#       pragma comment(lib, "libpng.lib")
#       pragma comment(lib, "libprotobuf.lib")
#       pragma comment(lib, "libtiff.lib")
#       pragma comment(lib, "libwebp.lib")
#       pragma comment(lib, "zlib.lib")
#       pragma comment(lib, "opencv_aruco310.lib")
#       pragma comment(lib, "opencv_bgsegm310.lib")
#       pragma comment(lib, "opencv_bioinspired310.lib")
#       pragma comment(lib, "opencv_calib3d310.lib")
#       pragma comment(lib, "opencv_ccalib310.lib")
#       pragma comment(lib, "opencv_core310.lib")
#       pragma comment(lib, "opencv_datasets310.lib")
#       pragma comment(lib, "opencv_dnn310.lib")
#       pragma comment(lib, "opencv_dpm310.lib")
#       pragma comment(lib, "opencv_face310.lib")
#       pragma comment(lib, "opencv_features2d310.lib")
#       pragma comment(lib, "opencv_flann310.lib")
#       pragma comment(lib, "opencv_fuzzy310.lib")
#       pragma comment(lib, "opencv_highgui310.lib")
#       pragma comment(lib, "opencv_imgcodecs310.lib")
#       pragma comment(lib, "opencv_imgproc310.lib")
#       pragma comment(lib, "opencv_line_descriptor310.lib")
#       pragma comment(lib, "opencv_ml310.lib")
#       pragma comment(lib, "opencv_objdetect310.lib")
#       pragma comment(lib, "opencv_optflow310.lib")
#       pragma comment(lib, "opencv_photo310.lib")
#       pragma comment(lib, "opencv_plot310.lib")
#       pragma comment(lib, "opencv_reg310.lib")
#       pragma comment(lib, "opencv_rgbd310.lib")
#       pragma comment(lib, "opencv_saliency310.lib")
#       pragma comment(lib, "opencv_shape310.lib")
#       pragma comment(lib, "opencv_stereo310.lib")
#       pragma comment(lib, "opencv_stitching310.lib")
#       pragma comment(lib, "opencv_structured_light310.lib")
#       pragma comment(lib, "opencv_superres310.lib")
#       pragma comment(lib, "opencv_surface_matching310.lib")
#       pragma comment(lib, "opencv_text310.lib")
#       pragma comment(lib, "opencv_tracking310.lib")
#       pragma comment(lib, "opencv_video310.lib")
#       pragma comment(lib, "opencv_videoio310.lib")
#       pragma comment(lib, "opencv_videostab310.lib")
#       pragma comment(lib, "opencv_viz310.lib")
#       pragma comment(lib, "opencv_xfeatures2d310.lib")
#       pragma comment(lib, "opencv_ximgproc310.lib")
#       pragma comment(lib, "opencv_xobjdetect310.lib")
#       pragma comment(lib, "opencv_xphoto310.lib")

#       ifdef _EVL_USE_VIZ
#           pragma comment(lib, "vtkalglib-6.3.lib")
#           pragma comment(lib, "vtkChartsCore-6.3.lib")
#           pragma comment(lib, "vtkCommonColor-6.3.lib")
#           pragma comment(lib, "vtkCommonComputationalGeometry-6.3.lib")
#           pragma comment(lib, "vtkCommonCore-6.3.lib")
#           pragma comment(lib, "vtkCommonDataModel-6.3.lib")
#           pragma comment(lib, "vtkCommonExecutionModel-6.3.lib")
#           pragma comment(lib, "vtkCommonMath-6.3.lib")
#           pragma comment(lib, "vtkCommonMisc-6.3.lib")
#           pragma comment(lib, "vtkCommonSystem-6.3.lib")
#           pragma comment(lib, "vtkCommonTransforms-6.3.lib")
#           pragma comment(lib, "vtkDICOMParser-6.3.lib")
#           pragma comment(lib, "vtkDomainsChemistry-6.3.lib")
#           pragma comment(lib, "vtkexoIIc-6.3.lib")
#           pragma comment(lib, "vtkexpat-6.3.lib")
#           pragma comment(lib, "vtkFiltersAMR-6.3.lib")
#           pragma comment(lib, "vtkFiltersCore-6.3.lib")
#           pragma comment(lib, "vtkFiltersExtraction-6.3.lib")
#           pragma comment(lib, "vtkFiltersFlowPaths-6.3.lib")
#           pragma comment(lib, "vtkFiltersGeneral-6.3.lib")
#           pragma comment(lib, "vtkFiltersGeneric-6.3.lib")
#           pragma comment(lib, "vtkFiltersGeometry-6.3.lib")
#           pragma comment(lib, "vtkFiltersHybrid-6.3.lib")
#           pragma comment(lib, "vtkFiltersHyperTree-6.3.lib")
#           pragma comment(lib, "vtkFiltersImaging-6.3.lib")
#           pragma comment(lib, "vtkFiltersModeling-6.3.lib")
#           pragma comment(lib, "vtkFiltersParallel-6.3.lib")
#           pragma comment(lib, "vtkFiltersParallelImaging-6.3.lib")
#           pragma comment(lib, "vtkFiltersProgrammable-6.3.lib")
#           pragma comment(lib, "vtkFiltersSelection-6.3.lib")
#           pragma comment(lib, "vtkFiltersSMP-6.3.lib")
#           pragma comment(lib, "vtkFiltersSources-6.3.lib")
#           pragma comment(lib, "vtkFiltersStatistics-6.3.lib")
#           pragma comment(lib, "vtkFiltersTexture-6.3.lib")
#           pragma comment(lib, "vtkFiltersVerdict-6.3.lib")
#           pragma comment(lib, "vtkfreetype-6.3.lib")
#           pragma comment(lib, "vtkftgl-6.3.lib")
#           pragma comment(lib, "vtkGeovisCore-6.3.lib")
#           pragma comment(lib, "vtkgl2ps-6.3.lib")
#           pragma comment(lib, "vtkhdf5-6.3.lib")
#           pragma comment(lib, "vtkhdf5_hl-6.3.lib")
#           pragma comment(lib, "vtkImagingColor-6.3.lib")
#           pragma comment(lib, "vtkImagingCore-6.3.lib")
#           pragma comment(lib, "vtkImagingFourier-6.3.lib")
#           pragma comment(lib, "vtkImagingGeneral-6.3.lib")
#           pragma comment(lib, "vtkImagingHybrid-6.3.lib")
#           pragma comment(lib, "vtkImagingMath-6.3.lib")
#           pragma comment(lib, "vtkImagingMorphological-6.3.lib")
#           pragma comment(lib, "vtkImagingSources-6.3.lib")
#           pragma comment(lib, "vtkImagingStatistics-6.3.lib")
#           pragma comment(lib, "vtkImagingStencil-6.3.lib")
#           pragma comment(lib, "vtkInfovisCore-6.3.lib")
#           pragma comment(lib, "vtkInfovisLayout-6.3.lib")
#           pragma comment(lib, "vtkInteractionImage-6.3.lib")
#           pragma comment(lib, "vtkInteractionStyle-6.3.lib")
#           pragma comment(lib, "vtkInteractionWidgets-6.3.lib")
#           pragma comment(lib, "vtkIOAMR-6.3.lib")
#           pragma comment(lib, "vtkIOCore-6.3.lib")
#           pragma comment(lib, "vtkIOEnSight-6.3.lib")
#           pragma comment(lib, "vtkIOExodus-6.3.lib")
#           pragma comment(lib, "vtkIOExport-6.3.lib")
#           pragma comment(lib, "vtkIOGeometry-6.3.lib")
#           pragma comment(lib, "vtkIOImage-6.3.lib")
#           pragma comment(lib, "vtkIOImport-6.3.lib")
#           pragma comment(lib, "vtkIOInfovis-6.3.lib")
#           pragma comment(lib, "vtkIOLegacy-6.3.lib")
#           pragma comment(lib, "vtkIOLSDyna-6.3.lib")
#           pragma comment(lib, "vtkIOMINC-6.3.lib")
#           pragma comment(lib, "vtkIOMovie-6.3.lib")
#           pragma comment(lib, "vtkIONetCDF-6.3.lib")
#           pragma comment(lib, "vtkIOParallel-6.3.lib")
#           pragma comment(lib, "vtkIOParallelXML-6.3.lib")
#           pragma comment(lib, "vtkIOPLY-6.3.lib")
#           pragma comment(lib, "vtkIOSQL-6.3.lib")
#           pragma comment(lib, "vtkIOVideo-6.3.lib")
#           pragma comment(lib, "vtkIOXML-6.3.lib")
#           pragma comment(lib, "vtkIOXMLParser-6.3.lib")
#           pragma comment(lib, "vtkjpeg-6.3.lib")
#           pragma comment(lib, "vtkjsoncpp-6.3.lib")
#           pragma comment(lib, "vtklibxml2-6.3.lib")
#           pragma comment(lib, "vtkmetaio-6.3.lib")
#           pragma comment(lib, "vtkNetCDF-6.3.lib")
#           pragma comment(lib, "vtkNetCDF_cxx-6.3.lib")
#           pragma comment(lib, "vtkoggtheora-6.3.lib")
#           pragma comment(lib, "vtkParallelCore-6.3.lib")
#           pragma comment(lib, "vtkpng-6.3.lib")
#           pragma comment(lib, "vtkproj4-6.3.lib")
#           pragma comment(lib, "vtkRenderingAnnotation-6.3.lib")
#           pragma comment(lib, "vtkRenderingContext2D-6.3.lib")
#           pragma comment(lib, "vtkRenderingContextOpenGL-6.3.lib")
#           pragma comment(lib, "vtkRenderingCore-6.3.lib")
#           pragma comment(lib, "vtkRenderingFreeType-6.3.lib")
#           pragma comment(lib, "vtkRenderingGL2PS-6.3.lib")
#           pragma comment(lib, "vtkRenderingImage-6.3.lib")
#           pragma comment(lib, "vtkRenderingLabel-6.3.lib")
#           pragma comment(lib, "vtkRenderingLIC-6.3.lib")
#           pragma comment(lib, "vtkRenderingLOD-6.3.lib")
#           pragma comment(lib, "vtkRenderingOpenGL-6.3.lib")
#           pragma comment(lib, "vtkRenderingVolume-6.3.lib")
#           pragma comment(lib, "vtkRenderingVolumeOpenGL-6.3.lib")
#           pragma comment(lib, "vtksqlite-6.3.lib")
#           pragma comment(lib, "vtksys-6.3.lib")
#           pragma comment(lib, "vtktiff-6.3.lib")
#           pragma comment(lib, "vtkverdict-6.3.lib")
#           pragma comment(lib, "vtkViewsContext2D-6.3.lib")
#           pragma comment(lib, "vtkViewsCore-6.3.lib")
#           pragma comment(lib, "vtkViewsInfovis-6.3.lib")
#           pragma comment(lib, "vtkzlib-6.3.lib")
#       endif // End of '_EVL_USE_VIZ'

#   endif // End of '_DEBUG'

#   pragma comment(lib, "opengl32.lib")
#   pragma comment(lib, "vfw32.lib")

#endif // End of '_WIN32'

#endif // End of '__OPENCV_ALL__'
